version: '3.7'

services:

  mui_system:
    container_name: mui_system
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/mui_system'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
